# App Engine configuration (alternative to Cloud Run)
runtime: python311
entrypoint: streamlit run app_multiuser.py --server.port=$PORT --server.address=0.0.0.0

instance_class: F4_1G

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

env_variables:
  CHUNK_SIZE: '2000'
  CHUNK_OVERLAP: '400'
  TOP_K_RESULTS: '8'
  CONTEXT_WINDOW: '6'

# Note: Set OPENAI_API_KEY and XAI_API_KEY via Secret Manager
