# Cloud Build configuration for automated deployments
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/enterprise-rag:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/enterprise-rag:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/enterprise-rag:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/enterprise-rag:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'enterprise-rag'
      - '--image'
      - 'gcr.io/$PROJECT_ID/enterprise-rag:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'CHUNK_SIZE=2000,CHUNK_OVERLAP=400,TOP_K_RESULTS=8,CONTEXT_WINDOW=6'

images:
  - 'gcr.io/$PROJECT_ID/enterprise-rag:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/enterprise-rag:latest'

timeout: '1200s'
