version: '3.8'

services:
  regulatory-rag:
    build: .
    container_name: regulatory-rag-app
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
    volumes:
      - ./user_data:/app/user_data
      - ./onestream_vectordb:/app/onestream_vectordb
      - ./onestream_kb.json:/app/onestream_kb.json
      - ./users.json:/app/users.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
